### ISSUE TITLE
hydromt: setup pipes

### ISSUE THREAD

**Issue by hboisgon** [Deltares/HYDROLIB#63] opened 2022-07-19 13:39 UTC
Add 1D pipes to the branches via new setup_pipes method.
Includes geometry + roughness + cross-sections

We could think of two methods to setup_pipes:

1. From pipe shapefile with required values for invert level upstream and downstream
2. From pipe or road shapefile and fill invert level based on 1D DEM minus a fixed depth (eg DEM - 5m)

**Comment by xldeltares** [comment] 2022-07-29 16:02
@xldeltares needs to fix the duplicated network ids in the mesh file. Potential thing to check: the precision of the points, the convention for generating node ids. reference: dfm.py scripts from delft3dfmpy bangkok

**Comment by xldeltares** [comment] 2022-08-16 09:38
The issue is  fixed in hydrolib-core (https://github.com/Deltares/HYDROLIB-core/tree/fix/302_duplicated_node_ids). Pull requests are pending.

**Closed** 2022-09-02 13:46 UTC
